source 'https://cdn.cocoapods.org/'

install! 'cocoapods',
         :generate_multiple_pod_projects => true

platform :ios, '11.0'

target 'Muun' do
  use_frameworks! :linkage => :static

  pod 'core/all', :path => '../core', :testspecs => ['Tests'] 

  # Animations
  pod 'lottie-ios', '3.0.6'

  # This dependencies are fixed at core.podspec
  # Firebase
  pod 'GoogleUtilities'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  # GoogleDrive
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/Drive'
  pod 'SwiftLint', '0.50.1' # Keep in mind you will need to modify swiftlint.yml
  pod 'SwiftGen', '~> 6.0'
  
  target 'falconTests' do
      inherit! :search_paths
  end
  
end

target 'falconPushNotifications' do
  use_frameworks! :linkage => :static

  pod 'core/notifications', :path => '../core'
end

target 'falconUITests' do
  use_frameworks! :linkage => :static

  pod 'core/all', :path => '../core'
end

pre_install do |installer|
    # XCode runs scripts in a custom env where GOPATH is missing, so we store it in a file the build script can find
    File.open('.gopath', 'w') {|f| f.write(ENV["GOPATH"]) }

    `../../tools/libwallet-ios.sh`
end

def fix_config(config)
  # https://github.com/CocoaPods/CocoaPods/issues/8891#issuecomment-546636698
  if config.build_settings['DEVELOPMENT_TEAM'].nil?
    config.build_settings['DEVELOPMENT_TEAM'] = '5YYLBTUB6W'
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
        fix_config(config)
    end
    project.targets.each do |target|
      target.build_configurations.each do |config|
        fix_config(config)
      end
    end
  end
end
