// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: storage_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullValue int32

const (
	NullValue_NULL_VALUE NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_service_proto_enumTypes[0].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_storage_service_proto_enumTypes[0]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Struct struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fields map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_storage_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Struct) GetFields() map[string]*Value {
	if x != nil {
		return x.xxx_hidden_Fields
	}
	return nil
}

func (x *Struct) SetFields(v map[string]*Value) {
	x.xxx_hidden_Fields = v
}

type Struct_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unordered map of dynamically typed values
	Fields map[string]*Value
}

func (b0 Struct_builder) Build() *Struct {
	m0 := &Struct{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Fields = b.Fields
	return m0
}

type Value struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isValue_Kind           `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_storage_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Value) GetNullValue() NullValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_NullValue); ok {
			return x.NullValue
		}
	}
	return NullValue_NULL_VALUE
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) SetNullValue(v NullValue) {
	x.xxx_hidden_Kind = &value_NullValue{v}
}

func (x *Value) SetDoubleValue(v float64) {
	x.xxx_hidden_Kind = &value_DoubleValue{v}
}

func (x *Value) SetIntValue(v int32) {
	x.xxx_hidden_Kind = &value_IntValue{v}
}

func (x *Value) SetLongValue(v int64) {
	x.xxx_hidden_Kind = &value_LongValue{v}
}

func (x *Value) SetStringValue(v string) {
	x.xxx_hidden_Kind = &value_StringValue{v}
}

func (x *Value) SetBoolValue(v bool) {
	x.xxx_hidden_Kind = &value_BoolValue{v}
}

func (x *Value) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Value) HasNullValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_NullValue)
	return ok
}

func (x *Value) HasDoubleValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_DoubleValue)
	return ok
}

func (x *Value) HasIntValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_IntValue)
	return ok
}

func (x *Value) HasLongValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_LongValue)
	return ok
}

func (x *Value) HasStringValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_StringValue)
	return ok
}

func (x *Value) HasBoolValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_BoolValue)
	return ok
}

func (x *Value) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Value) ClearNullValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_NullValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearDoubleValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_DoubleValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearIntValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_IntValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearLongValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_LongValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearStringValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_StringValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearBoolValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_BoolValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Value_Kind_not_set_case case_Value_Kind = 0
const Value_NullValue_case case_Value_Kind = 1
const Value_DoubleValue_case case_Value_Kind = 2
const Value_IntValue_case case_Value_Kind = 3
const Value_LongValue_case case_Value_Kind = 4
const Value_StringValue_case case_Value_Kind = 5
const Value_BoolValue_case case_Value_Kind = 6

func (x *Value) WhichKind() case_Value_Kind {
	if x == nil {
		return Value_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *value_NullValue:
		return Value_NullValue_case
	case *value_DoubleValue:
		return Value_DoubleValue_case
	case *value_IntValue:
		return Value_IntValue_case
	case *value_LongValue:
		return Value_LongValue_case
	case *value_StringValue:
		return Value_StringValue_case
	case *value_BoolValue:
		return Value_BoolValue_case
	default:
		return Value_Kind_not_set_case
	}
}

type Value_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	NullValue   *NullValue
	DoubleValue *float64
	IntValue    *int32
	LongValue   *int64
	StringValue *string
	BoolValue   *bool
	// -- end of xxx_hidden_Kind
}

func (b0 Value_builder) Build() *Value {
	m0 := &Value{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NullValue != nil {
		x.xxx_hidden_Kind = &value_NullValue{*b.NullValue}
	}
	if b.DoubleValue != nil {
		x.xxx_hidden_Kind = &value_DoubleValue{*b.DoubleValue}
	}
	if b.IntValue != nil {
		x.xxx_hidden_Kind = &value_IntValue{*b.IntValue}
	}
	if b.LongValue != nil {
		x.xxx_hidden_Kind = &value_LongValue{*b.LongValue}
	}
	if b.StringValue != nil {
		x.xxx_hidden_Kind = &value_StringValue{*b.StringValue}
	}
	if b.BoolValue != nil {
		x.xxx_hidden_Kind = &value_BoolValue{*b.BoolValue}
	}
	return m0
}

type case_Value_Kind protoreflect.FieldNumber

func (x case_Value_Kind) String() string {
	md := file_storage_service_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isValue_Kind interface {
	isValue_Kind()
}

type value_NullValue struct {
	NullValue NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=proto.NullValue,oneof"`
}

type value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type value_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type value_LongValue struct {
	LongValue int64 `protobuf:"varint,4,opt,name=long_value,json=longValue,proto3,oneof"`
}

type value_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type value_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*value_NullValue) isValue_Kind() {}

func (*value_DoubleValue) isValue_Kind() {}

func (*value_IntValue) isValue_Kind() {}

func (*value_LongValue) isValue_Kind() {}

func (*value_StringValue) isValue_Kind() {}

func (*value_BoolValue) isValue_Kind() {}

type SaveRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_storage_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *SaveRequest) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *SaveRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *SaveRequest) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *SaveRequest) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *SaveRequest) ClearValue() {
	x.xxx_hidden_Value = nil
}

type SaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value *Value
}

func (b0 SaveRequest_builder) Build() *SaveRequest {
	m0 := &SaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

type GetRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_storage_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *GetRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	return m0
}

type GetResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,1,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_storage_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetResponse) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *GetResponse) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *GetResponse) ClearValue() {
	x.xxx_hidden_Value = nil
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *Value
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_storage_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *DeleteRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key string
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	return m0
}

type SaveBatchRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *Struct                `protobuf:"bytes,1,opt,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveBatchRequest) Reset() {
	*x = SaveBatchRequest{}
	mi := &file_storage_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBatchRequest) ProtoMessage() {}

func (x *SaveBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveBatchRequest) GetItems() *Struct {
	if x != nil {
		return x.xxx_hidden_Items
	}
	return nil
}

func (x *SaveBatchRequest) SetItems(v *Struct) {
	x.xxx_hidden_Items = v
}

func (x *SaveBatchRequest) HasItems() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Items != nil
}

func (x *SaveBatchRequest) ClearItems() {
	x.xxx_hidden_Items = nil
}

type SaveBatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items *Struct
}

func (b0 SaveBatchRequest_builder) Build() *SaveBatchRequest {
	m0 := &SaveBatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = b.Items
	return m0
}

type GetBatchRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Keys []string               `protobuf:"bytes,1,rep,name=keys,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBatchRequest) Reset() {
	*x = GetBatchRequest{}
	mi := &file_storage_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchRequest) ProtoMessage() {}

func (x *GetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBatchRequest) GetKeys() []string {
	if x != nil {
		return x.xxx_hidden_Keys
	}
	return nil
}

func (x *GetBatchRequest) SetKeys(v []string) {
	x.xxx_hidden_Keys = v
}

type GetBatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Keys []string
}

func (b0 GetBatchRequest_builder) Build() *GetBatchRequest {
	m0 := &GetBatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Keys = b.Keys
	return m0
}

type GetBatchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *Struct                `protobuf:"bytes,1,opt,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBatchResponse) Reset() {
	*x = GetBatchResponse{}
	mi := &file_storage_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchResponse) ProtoMessage() {}

func (x *GetBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBatchResponse) GetItems() *Struct {
	if x != nil {
		return x.xxx_hidden_Items
	}
	return nil
}

func (x *GetBatchResponse) SetItems(v *Struct) {
	x.xxx_hidden_Items = v
}

func (x *GetBatchResponse) HasItems() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Items != nil
}

func (x *GetBatchResponse) ClearItems() {
	x.xxx_hidden_Items = nil
}

type GetBatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items *Struct
}

func (b0 GetBatchResponse_builder) Build() *GetBatchResponse {
	m0 := &GetBatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = b.Items
	return m0
}

var File_storage_service_proto protoreflect.FileDescriptor

var file_storage_service_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x06,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x47, 0x0a, 0x0b, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xed, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x31, 0x0a, 0x0a,
	0x6e, 0x75, 0x6c, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x22, 0x43, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x31, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x37, 0x0a,
	0x10, 0x53, 0x61, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x37, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0x1b, 0x0a, 0x09, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x55, 0x4c, 0x4c, 0x5f, 0x56, 0x41, 0x4c, 0x55,
	0x45, 0x10, 0x00, 0x32, 0xa5, 0x02, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3c, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x75, 0x6e, 0x2f, 0x6c,
	0x69, 0x62, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var file_storage_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_storage_service_proto_goTypes = []any{
	(NullValue)(0),           // 0: proto.NullValue
	(*Struct)(nil),           // 1: proto.Struct
	(*Value)(nil),            // 2: proto.Value
	(*SaveRequest)(nil),      // 3: proto.SaveRequest
	(*GetRequest)(nil),       // 4: proto.GetRequest
	(*GetResponse)(nil),      // 5: proto.GetResponse
	(*DeleteRequest)(nil),    // 6: proto.DeleteRequest
	(*SaveBatchRequest)(nil), // 7: proto.SaveBatchRequest
	(*GetBatchRequest)(nil),  // 8: proto.GetBatchRequest
	(*GetBatchResponse)(nil), // 9: proto.GetBatchResponse
	nil,                      // 10: proto.Struct.FieldsEntry
	(*emptypb.Empty)(nil),    // 11: google.protobuf.Empty
}
var file_storage_service_proto_depIdxs = []int32{
	10, // 0: proto.Struct.fields:type_name -> proto.Struct.FieldsEntry
	0,  // 1: proto.Value.null_value:type_name -> proto.NullValue
	2,  // 2: proto.SaveRequest.value:type_name -> proto.Value
	2,  // 3: proto.GetResponse.value:type_name -> proto.Value
	1,  // 4: proto.SaveBatchRequest.items:type_name -> proto.Struct
	1,  // 5: proto.GetBatchResponse.items:type_name -> proto.Struct
	2,  // 6: proto.Struct.FieldsEntry.value:type_name -> proto.Value
	3,  // 7: proto.StorageService.Save:input_type -> proto.SaveRequest
	4,  // 8: proto.StorageService.Get:input_type -> proto.GetRequest
	6,  // 9: proto.StorageService.Delete:input_type -> proto.DeleteRequest
	7,  // 10: proto.StorageService.SaveBatch:input_type -> proto.SaveBatchRequest
	8,  // 11: proto.StorageService.GetBatch:input_type -> proto.GetBatchRequest
	11, // 12: proto.StorageService.Save:output_type -> google.protobuf.Empty
	5,  // 13: proto.StorageService.Get:output_type -> proto.GetResponse
	11, // 14: proto.StorageService.Delete:output_type -> google.protobuf.Empty
	11, // 15: proto.StorageService.SaveBatch:output_type -> google.protobuf.Empty
	9,  // 16: proto.StorageService.GetBatch:output_type -> proto.GetBatchResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_storage_service_proto_init() }
func file_storage_service_proto_init() {
	if File_storage_service_proto != nil {
		return
	}
	file_storage_service_proto_msgTypes[1].OneofWrappers = []any{
		(*value_NullValue)(nil),
		(*value_DoubleValue)(nil),
		(*value_IntValue)(nil),
		(*value_LongValue)(nil),
		(*value_StringValue)(nil),
		(*value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_service_proto_rawDesc), len(file_storage_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_service_proto_goTypes,
		DependencyIndexes: file_storage_service_proto_depIdxs,
		EnumInfos:         file_storage_service_proto_enumTypes,
		MessageInfos:      file_storage_service_proto_msgTypes,
	}.Build()
	File_storage_service_proto = out.File
	file_storage_service_proto_goTypes = nil
	file_storage_service_proto_depIdxs = nil
}
