// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: wallet_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_DeleteWallet_FullMethodName                  = "/rpc.WalletService/DeleteWallet"
	WalletService_NfcTransmit_FullMethodName                   = "/rpc.WalletService/NfcTransmit"
	WalletService_StartDiagnosticSession_FullMethodName        = "/rpc.WalletService/StartDiagnosticSession"
	WalletService_PerformDiagnosticScanForUtxos_FullMethodName = "/rpc.WalletService/PerformDiagnosticScanForUtxos"
	WalletService_SubmitDiagnosticLog_FullMethodName           = "/rpc.WalletService/SubmitDiagnosticLog"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	DeleteWallet(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*OperationStatus, error)
	// V2 - use then discard API
	NfcTransmit(ctx context.Context, in *NfcTransmitRequest, opts ...grpc.CallOption) (*NfcTransmitResponse, error)
	// Diagnostic Mode API
	StartDiagnosticSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DiagnosticSessionDescriptor, error)
	PerformDiagnosticScanForUtxos(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanProgressUpdate], error)
	SubmitDiagnosticLog(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (*DiagnosticSubmitStatus, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) DeleteWallet(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, WalletService_DeleteWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) NfcTransmit(ctx context.Context, in *NfcTransmitRequest, opts ...grpc.CallOption) (*NfcTransmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NfcTransmitResponse)
	err := c.cc.Invoke(ctx, WalletService_NfcTransmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) StartDiagnosticSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DiagnosticSessionDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticSessionDescriptor)
	err := c.cc.Invoke(ctx, WalletService_StartDiagnosticSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PerformDiagnosticScanForUtxos(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalletService_ServiceDesc.Streams[0], WalletService_PerformDiagnosticScanForUtxos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DiagnosticSessionDescriptor, ScanProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_PerformDiagnosticScanForUtxosClient = grpc.ServerStreamingClient[ScanProgressUpdate]

func (c *walletServiceClient) SubmitDiagnosticLog(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (*DiagnosticSubmitStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticSubmitStatus)
	err := c.cc.Invoke(ctx, WalletService_SubmitDiagnosticLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
type WalletServiceServer interface {
	DeleteWallet(context.Context, *EmptyMessage) (*OperationStatus, error)
	// V2 - use then discard API
	NfcTransmit(context.Context, *NfcTransmitRequest) (*NfcTransmitResponse, error)
	// Diagnostic Mode API
	StartDiagnosticSession(context.Context, *emptypb.Empty) (*DiagnosticSessionDescriptor, error)
	PerformDiagnosticScanForUtxos(*DiagnosticSessionDescriptor, grpc.ServerStreamingServer[ScanProgressUpdate]) error
	SubmitDiagnosticLog(context.Context, *DiagnosticSessionDescriptor) (*DiagnosticSubmitStatus, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) DeleteWallet(context.Context, *EmptyMessage) (*OperationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWallet not implemented")
}
func (UnimplementedWalletServiceServer) NfcTransmit(context.Context, *NfcTransmitRequest) (*NfcTransmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NfcTransmit not implemented")
}
func (UnimplementedWalletServiceServer) StartDiagnosticSession(context.Context, *emptypb.Empty) (*DiagnosticSessionDescriptor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDiagnosticSession not implemented")
}
func (UnimplementedWalletServiceServer) PerformDiagnosticScanForUtxos(*DiagnosticSessionDescriptor, grpc.ServerStreamingServer[ScanProgressUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method PerformDiagnosticScanForUtxos not implemented")
}
func (UnimplementedWalletServiceServer) SubmitDiagnosticLog(context.Context, *DiagnosticSessionDescriptor) (*DiagnosticSubmitStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDiagnosticLog not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_DeleteWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DeleteWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_DeleteWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DeleteWallet(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_NfcTransmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NfcTransmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).NfcTransmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_NfcTransmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).NfcTransmit(ctx, req.(*NfcTransmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_StartDiagnosticSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).StartDiagnosticSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_StartDiagnosticSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).StartDiagnosticSession(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PerformDiagnosticScanForUtxos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiagnosticSessionDescriptor)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServiceServer).PerformDiagnosticScanForUtxos(m, &grpc.GenericServerStream[DiagnosticSessionDescriptor, ScanProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_PerformDiagnosticScanForUtxosServer = grpc.ServerStreamingServer[ScanProgressUpdate]

func _WalletService_SubmitDiagnosticLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticSessionDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SubmitDiagnosticLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SubmitDiagnosticLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SubmitDiagnosticLog(ctx, req.(*DiagnosticSessionDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteWallet",
			Handler:    _WalletService_DeleteWallet_Handler,
		},
		{
			MethodName: "NfcTransmit",
			Handler:    _WalletService_NfcTransmit_Handler,
		},
		{
			MethodName: "StartDiagnosticSession",
			Handler:    _WalletService_StartDiagnosticSession_Handler,
		},
		{
			MethodName: "SubmitDiagnosticLog",
			Handler:    _WalletService_SubmitDiagnosticLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PerformDiagnosticScanForUtxos",
			Handler:       _WalletService_PerformDiagnosticScanForUtxos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wallet_service.proto",
}
