// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: wallet_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_wallet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type EmptyMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 EmptyMessage_builder) Build() *EmptyMessage {
	m0 := &EmptyMessage{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type OperationStatus struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status string                 `protobuf:"bytes,1,opt,name=status,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_wallet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OperationStatus) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *OperationStatus) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

type OperationStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status string
}

func (b0 OperationStatus_builder) Build() *OperationStatus {
	m0 := &OperationStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

type NfcTransmitRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ApduCommand []byte                 `protobuf:"bytes,1,opt,name=apduCommand,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NfcTransmitRequest) Reset() {
	*x = NfcTransmitRequest{}
	mi := &file_wallet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NfcTransmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NfcTransmitRequest) ProtoMessage() {}

func (x *NfcTransmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NfcTransmitRequest) GetApduCommand() []byte {
	if x != nil {
		return x.xxx_hidden_ApduCommand
	}
	return nil
}

func (x *NfcTransmitRequest) SetApduCommand(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ApduCommand = v
}

type NfcTransmitRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ApduCommand []byte
}

func (b0 NfcTransmitRequest_builder) Build() *NfcTransmitRequest {
	m0 := &NfcTransmitRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ApduCommand = b.ApduCommand
	return m0
}

type NfcTransmitResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ApduResponse []byte                 `protobuf:"bytes,1,opt,name=apduResponse,proto3"`
	xxx_hidden_StatusCode   int32                  `protobuf:"varint,2,opt,name=statusCode,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NfcTransmitResponse) Reset() {
	*x = NfcTransmitResponse{}
	mi := &file_wallet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NfcTransmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NfcTransmitResponse) ProtoMessage() {}

func (x *NfcTransmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NfcTransmitResponse) GetApduResponse() []byte {
	if x != nil {
		return x.xxx_hidden_ApduResponse
	}
	return nil
}

func (x *NfcTransmitResponse) GetStatusCode() int32 {
	if x != nil {
		return x.xxx_hidden_StatusCode
	}
	return 0
}

func (x *NfcTransmitResponse) SetApduResponse(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ApduResponse = v
}

func (x *NfcTransmitResponse) SetStatusCode(v int32) {
	x.xxx_hidden_StatusCode = v
}

type NfcTransmitResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ApduResponse []byte
	StatusCode   int32
}

func (b0 NfcTransmitResponse_builder) Build() *NfcTransmitResponse {
	m0 := &NfcTransmitResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ApduResponse = b.ApduResponse
	x.xxx_hidden_StatusCode = b.StatusCode
	return m0
}

type XpubResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SerializedXpub string                 `protobuf:"bytes,1,opt,name=serializedXpub,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *XpubResponse) Reset() {
	*x = XpubResponse{}
	mi := &file_wallet_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XpubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XpubResponse) ProtoMessage() {}

func (x *XpubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *XpubResponse) GetSerializedXpub() string {
	if x != nil {
		return x.xxx_hidden_SerializedXpub
	}
	return ""
}

func (x *XpubResponse) SetSerializedXpub(v string) {
	x.xxx_hidden_SerializedXpub = v
}

type XpubResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SerializedXpub string
}

func (b0 XpubResponse_builder) Build() *XpubResponse {
	m0 := &XpubResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SerializedXpub = b.SerializedXpub
	return m0
}

type SignMessageNfcCardRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageHex string                 `protobuf:"bytes,1,opt,name=messageHex,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SignMessageNfcCardRequest) Reset() {
	*x = SignMessageNfcCardRequest{}
	mi := &file_wallet_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageNfcCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageNfcCardRequest) ProtoMessage() {}

func (x *SignMessageNfcCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignMessageNfcCardRequest) GetMessageHex() string {
	if x != nil {
		return x.xxx_hidden_MessageHex
	}
	return ""
}

func (x *SignMessageNfcCardRequest) SetMessageHex(v string) {
	x.xxx_hidden_MessageHex = v
}

type SignMessageNfcCardRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageHex string
}

func (b0 SignMessageNfcCardRequest_builder) Build() *SignMessageNfcCardRequest {
	m0 := &SignMessageNfcCardRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageHex = b.MessageHex
	return m0
}

type SignMessageNfcCardResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SignedMessageHex string                 `protobuf:"bytes,1,opt,name=signedMessageHex,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SignMessageNfcCardResponse) Reset() {
	*x = SignMessageNfcCardResponse{}
	mi := &file_wallet_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageNfcCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageNfcCardResponse) ProtoMessage() {}

func (x *SignMessageNfcCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignMessageNfcCardResponse) GetSignedMessageHex() string {
	if x != nil {
		return x.xxx_hidden_SignedMessageHex
	}
	return ""
}

func (x *SignMessageNfcCardResponse) SetSignedMessageHex(v string) {
	x.xxx_hidden_SignedMessageHex = v
}

type SignMessageNfcCardResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SignedMessageHex string
}

func (b0 SignMessageNfcCardResponse_builder) Build() *SignMessageNfcCardResponse {
	m0 := &SignMessageNfcCardResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SignedMessageHex = b.SignedMessageHex
	return m0
}

type DiagnosticSessionDescriptor struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SessionId string                 `protobuf:"bytes,1,opt,name=sessionId,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DiagnosticSessionDescriptor) Reset() {
	*x = DiagnosticSessionDescriptor{}
	mi := &file_wallet_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticSessionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticSessionDescriptor) ProtoMessage() {}

func (x *DiagnosticSessionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiagnosticSessionDescriptor) GetSessionId() string {
	if x != nil {
		return x.xxx_hidden_SessionId
	}
	return ""
}

func (x *DiagnosticSessionDescriptor) SetSessionId(v string) {
	x.xxx_hidden_SessionId = v
}

type DiagnosticSessionDescriptor_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionId string
}

func (b0 DiagnosticSessionDescriptor_builder) Build() *DiagnosticSessionDescriptor {
	m0 := &DiagnosticSessionDescriptor{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionId = b.SessionId
	return m0
}

type ScanProgressUpdate struct {
	state             protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Update isScanProgressUpdate_Update `protobuf_oneof:"update"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanProgressUpdate) Reset() {
	*x = ScanProgressUpdate{}
	mi := &file_wallet_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanProgressUpdate) ProtoMessage() {}

func (x *ScanProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScanProgressUpdate) GetFoundUtxoReport() *FoundUtxoReport {
	if x != nil {
		if x, ok := x.xxx_hidden_Update.(*scanProgressUpdate_FoundUtxoReport); ok {
			return x.FoundUtxoReport
		}
	}
	return nil
}

func (x *ScanProgressUpdate) GetScanComplete() *ScanComplete {
	if x != nil {
		if x, ok := x.xxx_hidden_Update.(*scanProgressUpdate_ScanComplete); ok {
			return x.ScanComplete
		}
	}
	return nil
}

func (x *ScanProgressUpdate) SetFoundUtxoReport(v *FoundUtxoReport) {
	if v == nil {
		x.xxx_hidden_Update = nil
		return
	}
	x.xxx_hidden_Update = &scanProgressUpdate_FoundUtxoReport{v}
}

func (x *ScanProgressUpdate) SetScanComplete(v *ScanComplete) {
	if v == nil {
		x.xxx_hidden_Update = nil
		return
	}
	x.xxx_hidden_Update = &scanProgressUpdate_ScanComplete{v}
}

func (x *ScanProgressUpdate) HasUpdate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Update != nil
}

func (x *ScanProgressUpdate) HasFoundUtxoReport() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Update.(*scanProgressUpdate_FoundUtxoReport)
	return ok
}

func (x *ScanProgressUpdate) HasScanComplete() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Update.(*scanProgressUpdate_ScanComplete)
	return ok
}

func (x *ScanProgressUpdate) ClearUpdate() {
	x.xxx_hidden_Update = nil
}

func (x *ScanProgressUpdate) ClearFoundUtxoReport() {
	if _, ok := x.xxx_hidden_Update.(*scanProgressUpdate_FoundUtxoReport); ok {
		x.xxx_hidden_Update = nil
	}
}

func (x *ScanProgressUpdate) ClearScanComplete() {
	if _, ok := x.xxx_hidden_Update.(*scanProgressUpdate_ScanComplete); ok {
		x.xxx_hidden_Update = nil
	}
}

const ScanProgressUpdate_Update_not_set_case case_ScanProgressUpdate_Update = 0
const ScanProgressUpdate_FoundUtxoReport_case case_ScanProgressUpdate_Update = 1
const ScanProgressUpdate_ScanComplete_case case_ScanProgressUpdate_Update = 2

func (x *ScanProgressUpdate) WhichUpdate() case_ScanProgressUpdate_Update {
	if x == nil {
		return ScanProgressUpdate_Update_not_set_case
	}
	switch x.xxx_hidden_Update.(type) {
	case *scanProgressUpdate_FoundUtxoReport:
		return ScanProgressUpdate_FoundUtxoReport_case
	case *scanProgressUpdate_ScanComplete:
		return ScanProgressUpdate_ScanComplete_case
	default:
		return ScanProgressUpdate_Update_not_set_case
	}
}

type ScanProgressUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Update:
	FoundUtxoReport *FoundUtxoReport
	ScanComplete    *ScanComplete
	// -- end of xxx_hidden_Update
}

func (b0 ScanProgressUpdate_builder) Build() *ScanProgressUpdate {
	m0 := &ScanProgressUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FoundUtxoReport != nil {
		x.xxx_hidden_Update = &scanProgressUpdate_FoundUtxoReport{b.FoundUtxoReport}
	}
	if b.ScanComplete != nil {
		x.xxx_hidden_Update = &scanProgressUpdate_ScanComplete{b.ScanComplete}
	}
	return m0
}

type case_ScanProgressUpdate_Update protoreflect.FieldNumber

func (x case_ScanProgressUpdate_Update) String() string {
	md := file_wallet_service_proto_msgTypes[8].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isScanProgressUpdate_Update interface {
	isScanProgressUpdate_Update()
}

type scanProgressUpdate_FoundUtxoReport struct {
	FoundUtxoReport *FoundUtxoReport `protobuf:"bytes,1,opt,name=foundUtxoReport,proto3,oneof"`
}

type scanProgressUpdate_ScanComplete struct {
	ScanComplete *ScanComplete `protobuf:"bytes,2,opt,name=scanComplete,proto3,oneof"`
}

func (*scanProgressUpdate_FoundUtxoReport) isScanProgressUpdate_Update() {}

func (*scanProgressUpdate_ScanComplete) isScanProgressUpdate_Update() {}

type FoundUtxoReport struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address string                 `protobuf:"bytes,1,opt,name=address,proto3"`
	xxx_hidden_Amount  int64                  `protobuf:"varint,2,opt,name=amount,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FoundUtxoReport) Reset() {
	*x = FoundUtxoReport{}
	mi := &file_wallet_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundUtxoReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundUtxoReport) ProtoMessage() {}

func (x *FoundUtxoReport) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FoundUtxoReport) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *FoundUtxoReport) GetAmount() int64 {
	if x != nil {
		return x.xxx_hidden_Amount
	}
	return 0
}

func (x *FoundUtxoReport) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *FoundUtxoReport) SetAmount(v int64) {
	x.xxx_hidden_Amount = v
}

type FoundUtxoReport_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Address string
	Amount  int64
}

func (b0 FoundUtxoReport_builder) Build() *FoundUtxoReport {
	m0 := &FoundUtxoReport{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Amount = b.Amount
	return m0
}

type ScanComplete struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status string                 `protobuf:"bytes,1,opt,name=status,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanComplete) Reset() {
	*x = ScanComplete{}
	mi := &file_wallet_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanComplete) ProtoMessage() {}

func (x *ScanComplete) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScanComplete) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *ScanComplete) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

type ScanComplete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status string
}

func (b0 ScanComplete_builder) Build() *ScanComplete {
	m0 := &ScanComplete{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

type DiagnosticSubmitStatus struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StatusCode    int64                  `protobuf:"varint,1,opt,name=statusCode,proto3"`
	xxx_hidden_StatusMessage string                 `protobuf:"bytes,2,opt,name=statusMessage,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DiagnosticSubmitStatus) Reset() {
	*x = DiagnosticSubmitStatus{}
	mi := &file_wallet_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticSubmitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticSubmitStatus) ProtoMessage() {}

func (x *DiagnosticSubmitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiagnosticSubmitStatus) GetStatusCode() int64 {
	if x != nil {
		return x.xxx_hidden_StatusCode
	}
	return 0
}

func (x *DiagnosticSubmitStatus) GetStatusMessage() string {
	if x != nil {
		return x.xxx_hidden_StatusMessage
	}
	return ""
}

func (x *DiagnosticSubmitStatus) SetStatusCode(v int64) {
	x.xxx_hidden_StatusCode = v
}

func (x *DiagnosticSubmitStatus) SetStatusMessage(v string) {
	x.xxx_hidden_StatusMessage = v
}

type DiagnosticSubmitStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StatusCode    int64
	StatusMessage string
}

func (b0 DiagnosticSubmitStatus_builder) Build() *DiagnosticSubmitStatus {
	m0 := &DiagnosticSubmitStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StatusCode = b.StatusCode
	x.xxx_hidden_StatusMessage = b.StatusMessage
	return m0
}

var File_wallet_service_proto protoreflect.FileDescriptor

var file_wallet_service_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x4e, 0x66, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x64,
	0x75, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x61, 0x70, 0x64, 0x75, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x59, 0x0a, 0x13, 0x4e,
	0x66, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x70, 0x64, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x61, 0x70, 0x64, 0x75, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x58, 0x70, 0x75, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x64, 0x58, 0x70, 0x75, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x58, 0x70, 0x75, 0x62, 0x22, 0x3b,
	0x0a, 0x19, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x66, 0x63,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x78, 0x22, 0x48, 0x0a, 0x1a, 0x53,
	0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x66, 0x63, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x65, 0x78, 0x22, 0x3b, 0x0a, 0x1b, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x12, 0x53, 0x63, 0x61, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x74,
	0x78, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x37, 0x0a, 0x0c, 0x73,
	0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x43,
	0x0a, 0x0f, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5e, 0x0a, 0x16, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x92, 0x03, 0x0a, 0x0d,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x11, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x4e, 0x66, 0x63, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6d, 0x69, 0x74, 0x12, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x66, 0x63, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x66, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x20, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x5c, 0x0a, 0x1d,
	0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x53, 0x63, 0x61, 0x6e, 0x46, 0x6f, 0x72, 0x55, 0x74, 0x78, 0x6f, 0x73, 0x12, 0x20, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x1a,
	0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x54, 0x0a, 0x13, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x6f,
	0x67, 0x12, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74,
	0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x74, 0x69, 0x63, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x75, 0x75, 0x6e, 0x2f, 0x6c, 0x69, 0x62, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_wallet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wallet_service_proto_goTypes = []any{
	(*EmptyMessage)(nil),                // 0: rpc.EmptyMessage
	(*OperationStatus)(nil),             // 1: rpc.OperationStatus
	(*NfcTransmitRequest)(nil),          // 2: rpc.NfcTransmitRequest
	(*NfcTransmitResponse)(nil),         // 3: rpc.NfcTransmitResponse
	(*XpubResponse)(nil),                // 4: rpc.XpubResponse
	(*SignMessageNfcCardRequest)(nil),   // 5: rpc.SignMessageNfcCardRequest
	(*SignMessageNfcCardResponse)(nil),  // 6: rpc.SignMessageNfcCardResponse
	(*DiagnosticSessionDescriptor)(nil), // 7: rpc.DiagnosticSessionDescriptor
	(*ScanProgressUpdate)(nil),          // 8: rpc.ScanProgressUpdate
	(*FoundUtxoReport)(nil),             // 9: rpc.FoundUtxoReport
	(*ScanComplete)(nil),                // 10: rpc.ScanComplete
	(*DiagnosticSubmitStatus)(nil),      // 11: rpc.DiagnosticSubmitStatus
	(*emptypb.Empty)(nil),               // 12: google.protobuf.Empty
}
var file_wallet_service_proto_depIdxs = []int32{
	9,  // 0: rpc.ScanProgressUpdate.foundUtxoReport:type_name -> rpc.FoundUtxoReport
	10, // 1: rpc.ScanProgressUpdate.scanComplete:type_name -> rpc.ScanComplete
	0,  // 2: rpc.WalletService.DeleteWallet:input_type -> rpc.EmptyMessage
	2,  // 3: rpc.WalletService.NfcTransmit:input_type -> rpc.NfcTransmitRequest
	12, // 4: rpc.WalletService.StartDiagnosticSession:input_type -> google.protobuf.Empty
	7,  // 5: rpc.WalletService.PerformDiagnosticScanForUtxos:input_type -> rpc.DiagnosticSessionDescriptor
	7,  // 6: rpc.WalletService.SubmitDiagnosticLog:input_type -> rpc.DiagnosticSessionDescriptor
	1,  // 7: rpc.WalletService.DeleteWallet:output_type -> rpc.OperationStatus
	3,  // 8: rpc.WalletService.NfcTransmit:output_type -> rpc.NfcTransmitResponse
	7,  // 9: rpc.WalletService.StartDiagnosticSession:output_type -> rpc.DiagnosticSessionDescriptor
	8,  // 10: rpc.WalletService.PerformDiagnosticScanForUtxos:output_type -> rpc.ScanProgressUpdate
	11, // 11: rpc.WalletService.SubmitDiagnosticLog:output_type -> rpc.DiagnosticSubmitStatus
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_wallet_service_proto_init() }
func file_wallet_service_proto_init() {
	if File_wallet_service_proto != nil {
		return
	}
	file_wallet_service_proto_msgTypes[8].OneofWrappers = []any{
		(*scanProgressUpdate_FoundUtxoReport)(nil),
		(*scanProgressUpdate_ScanComplete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_service_proto_rawDesc), len(file_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_service_proto_goTypes,
		DependencyIndexes: file_wallet_service_proto_depIdxs,
		MessageInfos:      file_wallet_service_proto_msgTypes,
	}.Build()
	File_wallet_service_proto = out.File
	file_wallet_service_proto_goTypes = nil
	file_wallet_service_proto_depIdxs = nil
}
